roboflow:
  workspace: "cv-uoacw"
  project: "playing-cards-ow27d-5wxe0"
  version: 1
  model_format: "yolov8"
  api_key: ""

roboflow_inference:
  workspace: "0lauk0"
  project: "playing-cards-muou8"
  version: 1
  model_format: "yolov8"
  api_key: ""

data:
  path: "Playing-Cards-1/data.yaml"
  path_inference: "inference data/data.yaml"

model:
  name: "yolov8n.pt"
  epochs: 100
  batch_size: 16
  imgsz: 640
  freeze: 0

wandb:
  project: "yolov8-training"
  run_name: "inference-run_entireModel"
  artifact_name: "jojs-it-universitetet-i-k-benhavn/yolov8-training/best_model:v11"
  model_filename: "best.pt"